### ISSUE TITLE
Broken in v17R4

### ISSUE THREAD

**Issue by pol-itworx** [miyako/4d-plugin-custom-window#1]
4D app crashes when the form appears.

Very useful for a nice splash screen at startup.
A Windows version would be nice too.

Thanx for all the work you do.

Pascal.

**Comment by miyako** [comment]
it looks like 

``[window setStyleMask:NSBorderlessWindowMask];``

causes a crash.

disabling it means the title bar remains visible.

<img width="353" alt="スクリーンショット 2019-05-20 9 41 31" src="https://user-images.githubusercontent.com/1725068/57990642-77f1a200-7ae3-11e9-8902-a135d69bd9c8.png">

**Comment by miyako** [comment]
with the line comment out, the code would look like this:

```
$window:=Open form window("Form1";Modal form dialog box)
SET WINDOW TRANSPARENT ($window)
DIALOG("Form1")
```

**Comment by pol-itworx** [comment]
Cool, it works perfectly!
Splash screen:
![splash](https://user-images.githubusercontent.com/40853904/58015769-649f0080-7afc-11e9-9c66-bd96994cada9.png)

Overlay message:
![overlay](https://user-images.githubusercontent.com/40853904/58015814-7f717500-7afc-11e9-866b-1a2e31664371.png)

I'd like to see the same on windows...
Or 4D providing a transparent window class-feature...

Thanx a lot for the community!

Pascal.

**Comment by pol-itworx** [comment]
May I suggest a fade-in and fade-out feature?

Pascal.
